# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a07e91e8716535cfe67f26588de50ac853257245c92a83fed77deccf24f19350bbac0308efd0b9695cae50dc6d3989bb8cabb01f4fab2afe549b6ab520cd0ac

test:
  secret_key_base: e044717797c90941eaff380b7f09f0f8254bf33fe88b96c70d827a5128308935517e3670e96e6cc3390d7fd91054bb57c90757612bf1c7f9c595445d7ebb388f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
